### ISSUE TITLE
Using Other Ontologies

### ISSUE THREAD

**Issue by astarr97** [louadi/NEASE#5]
Hello,

I have been using NEASE (it seems great so far) and had a quick question.  I am wondering whether it is possible to use additional ontologies such as the human phenotype ontology with NEASE.  If yes, any suggestions on how I could do that?

Best, Alex.

**Comment by louadi** [comment]
Hi Alex,

I m happy to hear that NEASE is useful for you.

Unfortunately, adding more databases is not straightforward and could take some time since we need to pre-compute the node degree before. 

Is the human phenotype ontology a pathway in a classical sense like modules of proteins and complexes? Otherwise, it might not make much sense to add it, since the method is based on PPI evidence...and could you share a file of this database with pathways id, name, and genes id (preferably Entrez)?  

Best,
Zakaria

**Comment by astarr97** [comment]
Thanks for the quick reply!  It is not a classical set of pathways, but I would still be interested to see if any phenotypes are enriched for genes with altered PPIs.  Here is a link to the file for the database: https://drive.google.com/file/d/1Pj6iVrmr-HN7fQMV4XxVrb2b6N7b-V5u/view?usp=sharing.  1 indicates that a gene is associated with a term, 0 indicates it is not.

**Comment by louadi** [comment]
Hi Alex,

Sorry for the late reply I was off for the Easter break.

Could you help me out and prepare your database in a format similar to the one in http://consensuspathdb.org/  
[(file)](https://drive.google.com/file/d/1A-aLBdhqFy5kcmu5sKMDd3STzTz9fC9f/view?usp=sharing). So I can easily integrate it with the current one.

Best,
Zakaria
